apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tesla-monitor
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        # Zwiększone limity dla stabilności (bez Tesla proxy - mniej zasobów)
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1"
        # Zwiększony timeout dla długich operacji Tesla API
        run.googleapis.com/timeout: "900s"
        # Maksymalna liczba instancji
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      # Timeout dla kontenerów
      timeoutSeconds: 900
      containers:
      - image: europe-west1-docker.pkg.dev/off-peak-tesla-controller/cloud-run-source-deploy/tesla-monitor:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "off-peak-tesla-controller"
        - name: GOOGLE_CLOUD_STORAGE_BUCKET
          value: "tesla-monitor-data-off-peak-tesla-controller"
        # Zmienne środowiskowe dla Tesla Fleet API (bez proxy)
        - name: TESLA_TIMEOUT
          value: "90"
        - name: NODE_ENV
          value: "production"
        # Health check
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 300
          timeoutSeconds: 30
          failureThreshold: 3

        # Limity zasobów (zredukowane bez proxy)
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
  traffic:
  - percent: 100
    latestRevision: true 