apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tesla-monitor
  annotations:
    # OPTYMALIZACJA KOSZTÓW: Skalowanie do zera
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
    # Szybkie skalowanie w górę gdy potrzeba
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "1"
    # Szybkie wyłączanie gdy brak ruchu
    run.googleapis.com/timeout: "300"
spec:
  template:
    metadata:
      annotations:
        # KLUCZOWE: Skalowanie do zera dla optymalizacji kosztów
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
        # Szybkie cold start
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        # Timeout dla pojedynczego wywołania
        run.googleapis.com/timeout: "300"
    spec:
      # Timeout dla całego kontenera
      timeoutSeconds: 300
      containerConcurrency: 1
      containers:
      - name: tesla-monitor
        image: gcr.io/off-peak-tesla-controller/tesla-monitor:smart
        ports:
        - containerPort: 8080
        env:
        # KLUCZOWE: Wyłącz tryb continuous dla optymalizacji kosztów
        - name: CONTINUOUS_MODE
          value: "false"
        - name: GOOGLE_CLOUD_PROJECT
          value: "off-peak-tesla-controller"
        - name: GOOGLE_CLOUD_STORAGE_BUCKET
          value: "tesla-monitor-data-off-peak-tesla-controller"
        # Tesla API Configuration
        - name: TESLA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: tesla-client-id
              key: latest
        - name: TESLA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: tesla-client-secret
              key: latest
        - name: TESLA_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: tesla-refresh-token
              key: latest
        # Tesla HTTP Proxy Configuration (Smart Proxy Mode)
        - name: TESLA_SMART_PROXY_MODE
          value: "true"
        - name: TESLA_PROXY_AVAILABLE
          value: "true"
        - name: TESLA_HTTP_PROXY_HOST
          value: "localhost"
        - name: TESLA_HTTP_PROXY_PORT
          value: "4443"
        # Home Location
        - name: HOME_LATITUDE
          value: "52.334215"
        - name: HOME_LONGITUDE
          value: "20.937516"
        - name: HOME_RADIUS
          value: "0.03"
        resources:
          # OPTYMALIZACJA: Minimalne zasoby dla krótkich wywołań
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        # Health check - szybkie sprawdzenie
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        # Startup probe dla cold start
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12  # 60 sekund na startup 